[package]
name = "octo-squirrel-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octo-squirrel = { path = "../octo-squirrel" }
tokio = { version = "1.39.2", features = ["full"] }
tokio-stream = "0.1.15"
tokio-util = { version = "0.7.11", features = ["codec", "net"] }
tokio-native-tls = "0.3.1"
futures = "0.3.30"
log = "0.4.22"
log4rs = "1.3.0"
bytes = "1.7.1"
rand = { version = "0.8.5", features = ["small_rng"] }
dashmap = "5.5.3"
uuid = { version = "1.10.0", features = ["v4"] }
anyhow = "1.0.86"
sha2 = "0.10.8"
