[package]
name = "octo-squirrel-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octo-squirrel = { path = "../octo-squirrel" }
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = "0.1.16"
tokio-util = { version = "0.7.12", features = ["codec", "net"] }
futures = "0.3.30"
log = "0.4.22"
log4rs = "1.3.0"
bytes = "1.7.1"
digest = "0.10.7"
hmac = "0.12.1"
hkdf = "0.12.4"
md-5 = "0.10.6"
crc = "3.2.1"
sha1 = "0.10.6"
sha2 = "0.10.8"
sha3 = "0.10.8"
aes = "0.8.4"
ecb = "0.1.2"
aead = { version = "0.5.2", features = ["bytes"] }
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1"
generic-array = "0.14.7"

[[bin]]
name = "test"
path = "src/test.rs"
