[package]
name = "octo-squirrel-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octo-squirrel = { path = "../octo-squirrel", features = ["client", "server"] }
octo-squirrel-client = { path = "../octo-squirrel-client"}
octo-squirrel-server = { path = "../octo-squirrel-server"}
anyhow = "1.0.88"
console-subscriber = "0.4.0"
futures = "0.3.30"
log = "0.4.22"
log4rs = "1.3.0"
tokio = { version = "1.40.0", features = ["full", "tracing"] }

[[bin]]
name = "octo-squirrel-tracing-server"
path = "src/tracing-server.rs"

[[bin]]
name = "octo-squirrel-tracing-client"
path = "src/tracing-client.rs"
