[package]
name = "octo-squirrel-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octo-squirrel = { path = "../octo-squirrel" }
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.8", features = ["codec", "net"] }
futures = "0.3.28"
log = "0.4.20"
log4rs = "1.2.0"
bytes = "1.4.0"
digest = "0.10.7"
hmac = "0.12.1"
hkdf = "0.12.3"
md-5 = "0.10.5"
crc = "3.0.1"
sha1 = "0.10.5"
sha2 = "0.10.7"
sha3 = "0.10.8"
aes = "0.8.3"
ecb = "0.1.2"
aead = { version = "0.5.2", features = ["bytes"] }
aes-gcm = "0.10.2"
chacha20poly1305 = "0.10.1"
generic-array = "0.14.7"

[[bin]]
name = "test"
path = "src/test.rs"
