[package]
name = "octo-squirrel-test"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octo-squirrel = { path = "../octo-squirrel", features = ["client", "server"] }
octo-squirrel-client = { path = "../octo-squirrel-client" }
octo-squirrel-server = { path = "../octo-squirrel-server" }
anyhow = "1.0.97"
console-subscriber = "0.4.1"
rand = { version = "0.9.0", features = ["small_rng"] }
tokio = { version = "1.44.1", features = ["full", "tracing"] }

[dev-dependencies]
bytes = { version = "1.10.1" }
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "encrypt"
path = "src/benches/encrypt.rs"
harness = false

[[bench]]
name = "read_bytes"
path = "src/benches/read_bytes.rs"
harness = false
