[package]
name = "octo-squirrel-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octo-squirrel = { path = "../octo-squirrel", features = ["client", "server"] }
octo-squirrel-client = { path = "../octo-squirrel-client"}
octo-squirrel-server = { path = "../octo-squirrel-server"}
anyhow = "1.0.89"
bytes = { version = "1.7.2", features = ["serde"] }
console-subscriber = "0.4.0"
futures = "0.3.31"
log = "0.4.22"
log4rs = "1.3.0"
rand = { version = "0.8.5", features = ["small_rng"] }
tokio = { version = "1.40.0", features = ["full", "tracing"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "encrypt"
path = "src/benches/encrypt.rs"
harness = false

[[bench]]
name = "read_bytes"
path = "src/benches/read_bytes.rs"
harness = false