[package]
name = "octo-squirrel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["codec", "net"] }
tokio-stream = "0.1.15"
futures = "0.3.30"
bytes = "1.7.1"
base64ct = { version = "1.6.0", features = ["alloc"] }
uuid = { version = "1.10.0", features = ["v4"] }
rand = { version = "0.8.5", features = ["small_rng"] }
digest = "0.10.7"
hmac = "0.12.1"
hkdf = "0.12.4"
md-5 = "0.10.6"
crc = "3.2.1"
sha1 = "0.10.6"
sha2 = "0.10.8"
sha3 = "0.10.8"
aes = "0.8.4"
ecb = "0.1.2"
aead = { version = "0.5.2", features = ["bytes"] }
aes-gcm = "0.10.3"
chacha20poly1305 = "0.10.1"
generic-array = "0.14.7"
log = "0.4.22"
log4rs = "1.3.0"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.125"
blake3 = "1.5.3"
anyhow = "1.0.86"
dashmap = "5.5.3"
lru_time_cache = "0.11.11"
byte_string = "1.0.0"
