[package]
name = "octo-squirrel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["codec", "net"] }
bytes = "1.4.0"
futures = "0.3.28"
tokio-stream = "0.1.14"
hmac = "0.12.1"
hkdf = "0.12.3"
sha1 = "0.10.5"
sha2 = "0.10.7"
base64 = "0.21.2"
crc = "3.0.1"
aes = "0.8.3"
ecb = "0.1.1"
uuid = { version = "1.4.1", features = ["v4"] }
rand = { version = "0.8.5", features = ["small_rng"] }
aes-gcm = "0.10.2"
md-5 = "0.10.5"
generic-array = "0.14.7"
base64ct = { version = "1.6.0", features = ["alloc"] }
digest = "0.10.7"
chacha20poly1305 = "0.10.1"
log = "0.4.20"
log4rs = "1.2.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"