[package]
name = "octo-squirrel-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octo-squirrel = { path = "../octo-squirrel", features = ["server"] }
anyhow = "1.0.86"
bytes = "1.7.1"
futures = "0.3.30"
futures-util = { version = "=0.3.30", features = ["unstable", "bilock"] }
log = "0.4.22"
log4rs = "1.3.0"
rand = { version = "0.8.5", features = ["small_rng"] }
sha2 = "0.10.8"
tokio = { version = "1.39.3", features = ["full"] }
tokio-native-tls = "0.3.1"
tokio-stream = "0.1.15"
tokio-util = { version = "0.7.11", features = ["codec", "net"] }
uuid = { version = "1.10.0", features = ["v4"] }