name: release-test
on:
  workflow_dispatch:
   inputs:
    tag:
      description: 'Release Tag'
      required: true
      type: string
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --bin octo-squirrel-client --bin octo-squirrel-server
      - name: Zip
        run: |
          zip -q target/release/octo-squirrel-client-win.zip target/release/octo-squirrel-client.exe
          zip -q target/release/octo-squirrel-server-win.zip target/release/octo-squirrel-server.exe  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: octo-squirrel-windows
          path: |
            target/release/octo-squirrel-client-win.zip
            target/release/octo-squirrel-server-win.zip
          retention-days: 1
          overwrite: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  build:
    needs: build-on-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --bin octo-squirrel-client --bin octo-squirrel-server
      - name: Zip
        run: |
          zip -q target/release/octo-squirrel-client-linux.zip target/release/octo-squirrel-client
          zip -q target/release/octo-squirrel-server-linux.zip target/release/octo-squirrel-server
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: octo-squirrel-windows
          path: target/release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          files: |
            target/release/*.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
