name: release-test
on:
  workflow_dispatch
jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: Cargo build --release --bin octo-squirrel-client --bin octo-squirrel-server
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: octo-squirrel-windows
          path: |
            target/release/octo-squirrel-client.exe
            target/release/octo-squirrel-server.exe
          retention-days: 1
          overwrite: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  build:
    needs: build-on-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: octo-squirrel-windows
          path: target/release
      - name: Tag
        id: tag
        run: |
          echo "::set-output name=release_test_tag::PreRelease_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_test_tag }}
          files: |
            target/release/octo-squirrel-client
            target/release/octo-squirrel-client.exe
            target/release/octo-squirrel-server
            target/release/octo-squirrel-server.exe
          prerelease: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
